### ISSUE TITLE
Check Definitions for Columns

### ISSUE THREAD

**Issue by ChrisTheKnife** [ChrisTheKnife/fashion-recommender#8]
- What do the different columns in the CSVs mean? (e.g. FN, Active)
- Transaction_train: Is every row a single article purchase?
- Website :
[Kaggle H&M channel](https://www.kaggle.com/competitions/h-and-m-personalized-fashion-recommendations/discussion/305952)

- What do the different columns in the CSVs mean? (e.g. FN, Active)
- Transaction_train: Is every row a single article purchase?

- https://docs.google.com/spreadsheets/d/1QRc-rm3fWkIqeObKF44onolWD0LjCm5oi_SmT447rWg/edit?usp=sharing

Initial documentation in Google Spreadsheet [X], final docu as markdown in github repo [X].

**Comment by theflyingd** [comment]
https://www.kaggle.com/competitions/h-and-m-personalized-fashion-recommendations/discussion/305952
